# Generated by Django 5.0.6 on 2024-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('ongoing', 'ON GOING'), ('paused', 'PAUSED'), ('over', 'OVER')], default='ongoing', max_length=200)),
            ],
        ),
    ]
